### PR TITLE
LDAP Based Role Support

### PR DESCRIPTION
**Pull request by BillMedernach**
Implemented LDAP based roles with backwards compatibility for old versions of Hologram through configuration options.

Based directly on pull request #49 by @copumpkin 

@walterking

### CODE REVIEW

**Comment by copumpkin** [comment]
It looks like you have different indentation settings from the surrounding code. Not sure what the repo owners' policy on this is, but I prefer consistency if possible :smile: 

Could you also outline the main differences from my earlier PR?

**Comment by copumpkin** [comment]
My biggest concerns around my implementation (which I've been using for a few months) are that there's not a good "update LDAP when authorization failed" step, and that revoking access isn't automatic. The former is easy to add. The latter might require a different approach: we could have LDAP resync happen on a timer. That'd probably not be a big deal because the temporary AWS credentials we generate are already valid for a window. Alternately, we could just have LDAP not be cached and make a new LDAP request for every attempted credential issue. We'd probably need to include a little more information in the Holgoram protocol (who I claim to be as well as my signature) to make that efficient, but that's probably worth doing anyway. The "test every key against the provided signature" approach doesn't scale very well :smile:

**Comment by BillMedernach** [comment]
> It looks like you have different indentation settings from the surrounding code. Not sure what the repo owners' policy on this is, but I prefer consistency if possible :smile:

I agree. I'll fix that up. It's my first time writing Go and my Vim configuration doesn't seem to be configured properly for Go's tabs.

> My biggest concerns around my implementation (which I've been using for a few months) are that there's not a good "update LDAP when authorization failed" step

I'm not too concerned about this for now. If you revoke Hologram access from a user as Hologram is right now the same problem still exists. But good point - something we should certainly work towards.

As for the main differences from your PR, I changed the LDAP searches to use a configurable attribute and I made LDAP based roles optional on the server configuration.

**Comment by ikalinin** [comment]
@copumpkin, any other concerns? Otherwise I'm merging this PR.

**Comment by copumpkin** [comment]
Nope, I think it's generally fine, except for a couple of lingering indentation issues. It looks like the code is basically a cleaned-up and improved version of my PR, so after merging this I'll also close mine.

**Comment by ikalinin** [comment]
Merged.

**Comment by copumpkin** [comment]
Great, thanks :beers:

**Pull request merged**
