### PR TITLE
Fix protobuf reference paths

### PR DESCRIPTION
**Pull request by copumpkin**
They were out of sync with the other ones. They're autogenerated files and I didn't bother regenerating them but this seems sufficient to get it compiling again.

### CODE REVIEW

**Comment by copumpkin** [comment]
I don't _think_ the travis failure is related to this, but it's hard to be sure!

**Comment by frangarciam** [comment]
Thanks for the PR!

I think the tests are just github being flaky today, I'm having lots of issues downloading dependencies from here as well.

The good news is that your change is included in https://github.com/AdRoll/hologram/pull/27, which we're merging right now (in order for it to work we also need to modify the Godeps file so we can pull the right deps) so I'll close this one.

**Comment by zylad** [comment]
https://github.com/AdRoll/hologram/pull/27 has been merged, so this change is included there. Thanks for reporting, @copumpkin !

**Comment by copumpkin** [comment]
Great, thanks!

**Pull request closed without merging**
