### PR TITLE
Wrong path in the postinstall script.

### PR DESCRIPTION
**Pull request by dialtone**

### CODE REVIEW

**Comment by walterking** [comment]
what are you trying to do?  im not sure if the current command /should/ exist, but running it as a launchdaemon wont work because hologram me needs to be an agent to know the logged in user to be able to read the correct ssh directory

**Comment by dialtone** [comment]
Well it can be whatever but the install scripts put it in the Daemon
directory so if the right path is agents then we should install the plist
there.

**Comment by walterking** [comment]
oh, i get it.  i dont see how it could work currently - i bet you all have an error from hologram-me.plist in your syslog every boot.  the install script is probably the one that should be changed instead of postinstall for this to work as intended

**Comment by dialtone** [comment]
I think it currently works thanks to old copies of that file from older versions that still work as intended.

**Comment by dialtone** [comment]
alright, now switched to fix the installer

**Comment by walterking** [comment]
looks right to me 👍

**Pull request merged**
